### PR TITLE
fix(libs-api): fix warning export in yarn build

### PR DESCRIPTION
**Pull request by VienNguyen24hdev**

### CODE REVIEW

**Comment by webberwang** [comment]
Is there a solution without having to use `type`?

**Comment by VienNguyen24hdev** [comment]
> Is there a solution without having to use `type`? maybe some tsconfig settings

I'm still looking for. This is just a way to fix temporarily

**Comment by webberwang** [comment]
in this case extends does work better, but for importing `type`, will that warning always show?

**Comment by VienNguyen24hdev** [comment]
> in this case extends does work better, but for importing `type`, will that warning always show?
> 
> how come it doesn't show for react only nestjs?

I think it shows warning here because we export a type from a class WinstonLogger. It doesn't show if we export a regular type

**Comment by webberwang** [comment]
Oh I see now thanks

**Pull request closed without merging**
